### ISSUE TITLE
Create an AWS Lambda and Connect to API Gateway.

### ISSUE THREAD

**Issue by syedautherabbas** [100DaysOfCloud/100DaysOfCloudIdeas#17]
### Choose the category (Choose only one, delete the remaining)
- Serverless

If you know the sub-category that would help as well.
-Serverless Functions

### Choose the level of difficulty (Please only choose one, delete the remaining)

- Level 100 (Introductory)

### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)

-  AWS

### Do your best to calculate possible costs for free-tier and non-free-tier account
The AWS Lambda free usage tier includes **1M free requests per month and 400,000 GB-seconds of compute time per month

### If you know of any external resources, provide the links
- [AWS Lambda- Getting Started](https://aws.amazon.com/lambda/getting-started/)
- [API Gateway Getting Started](https://aws.amazon.com/api-gateway/getting-started/)
- [Connecting AWS Lambda and API Gateway](https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway-tutorial.html)
- [Securing the API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-to-api.html)

**Comment by what-name** [comment]
#16 
Lambda and APIGateway are not Level 100 but 200. Especially when securing the API with an access key. Creating this is somewhat easy after some experience, but saying this is Level100 is false hope. Participants will likely encounter some advanced problems such as choosing "Proxy" and integrating the two resources together, deploying the API Gateway after changes and using POSTMAN (which is not required without the API Access Key).

I think the API Access Key should be optional and this project bumped to 200.

**Comment by syedautherabbas** [comment]
@what-name in my opinion we should inculcate the idea of building anything with a security first approach, so included the API key as must ,but that could be anything else too with a security aspect is all.

As for complexity ,I thought we could see some of these below  patterns implemented for further levels as it will add a dash of challenge to exploring serverless functions offerings with various triggers

https://www.jeremydaly.com/serverless-microservice-patterns-for-aws/

Just my $0.2

**Comment by madebygps** [comment]
I agree level 200 for any FaaS really, security first, always.

**Comment by madebygps** [comment]
closing, please apply changes in PR https://github.com/100DaysOfCloud/100DaysOfCloudIdeas/pull/16#issuecomment-657239478
