### ISSUE TITLE
Setup docker on different virtual machines and create clustering using docker swarm 

### ISSUE THREAD

**Issue by KaranGauswami** [100DaysOfCloud/100DaysOfCloudIdeas#19]
### Choose the category (Choose only one, delete the remainging)
- DevOps

If you know the sub-category that would help as well.

### Choose the level of difficulty (Please only choose one, delete the remaining)

- Level 200 (Intermediate)

### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)

-  AWS
-  GCP
-  Azure

### Do your best to calculate possible costs for free-tier and non-free-tier account

- For AWS, In Free tier it Provides 750 hours of t2.micro Instances each month.  

### If you know of any external resources, provide the links

- [Docker](https://www.docker.com/)

**Comment by what-name** [comment]
### Category
COM04 - Containers

### Resources
- [Install Docker](https://docs.docker.com/engine/install/ubuntu/)
- [Get Started with Docker Swarm](https://docs.docker.com/engine/swarm/swarm-tutorial/)

## Misc
- This brings up a great point; what if a project can be done the exact same way on all providers? Should these go into UNI or that's for more unique, open-ended and finished-product oriented projects?

**Comment by omenking** [comment]
In Elastic Beanstalk I would put this Level 200, but would we say this is Level 300 unless its dead simple to launch a VM that has docker swarm on it?

**Comment by KaranGauswami** [comment]
@what-name The only different way of doing things would be to run some startup scripts on all platform while creating new instances.

**Comment by omenking** [comment]
Looks good to me proceed to create a project using template and submit a PR:
https://github.com/100DaysOfCloud/100DaysOfCloudIdeas/blob/master/Templates/PROJECT-TEMPLATE.md

**Comment by KaranGauswami** [comment]
@omenking In which cloud provider category this will fit ? This can be done on all Providers, We can even use different Providers for same project.

**Comment by madebygps** [comment]
@KaranGauswami Which ever you are most comfortable and can provide most details with.
