### ISSUE TITLE
A place for participants to ask for help or general questions

### ISSUE THREAD

**Issue by what-name** [100DaysOfCloud/100DaysOfCloudIdeas#2]
Currently there is no well-known place where participants can ask questions from the #100DaysOfCloud community. I think designating a seperate #questions channel on Discord would be a great idea for example. People with a small following on twitter do not have much access to direct help other than "3rd party" channels.
- Is Discord a good fit for this? Are there any drawbacks to using that platform?
- How would the Discord group be "promoted"? Invitation placed on the 100DaysOfCloud website for example?
- If not Discord, are there any easily accessible platforms that work well for this use-case?

**Comment by madebygps** [comment]
Great suggestion. Would be great to see how other communities handle this. Wondering if Discord is the best place. The less friction possible to submit and respond to questions, the better.

**Comment by donofriov** [comment]
I think slack is a better option for growing a community that is going to work together. The biggest benefit for me are slack threads. They allow you to compartmentalize conversations or help in a single place instead of trying to have multiple conversations in one long list. This becomes more of an issue as the community grows.

In terms of of channels I think it would be great to have general #100DaysOfCloud channels and then cloud service provider specific channels like we currently do but multiple for each provider. For example we could have #aws-challenges, #aws-help, #aws-resources, #aws-links, #gcp-challenges, #gcp-help, etc. Making channels more specific to the topic at hand allows for quicker and more relevant feedback.

**Comment by what-name** [comment]
@donofriov I would very much advocate against Slack. Using it without prior work environment experience is difficult, the signup and login process is utterly confusing. Apart from the threads feature (which is indeed great), I don't see any other benefit and multiple cons. People who are yet to start in IT and the Cloud have likely never used Slack before. I was personally one of them and had a lot of difficulty in figuring out simply how to log in to a workplace.

Discord has much less friction in both signing up, logging in and switching between servers. I'm not a fan of Discord because of their privacy issues, but it does seem like a great option for this. A lot of people aready have a Discord account and if they don't, getting started is super easy.

Another point I'd like to add is that Discord allows you to DM with users outside of a group. On Slack it is confined to the workplace, so if you don't log into that workspace often (which happens), your DMs can get lost. This is a small point but I think quite important. Building personal relationships is crucial for communities like this in my opinion.

**Comment by donofriov** [comment]
Ok then agree to disagree 😄 The signup process is the exact same as Discord, just accepting a signup link. It's just another chat service and they all have similar functionality so whatever works for the masses. I've just only ever used Discord for gaming/streaming so I may have a biased opinion about it.

That being said, I still think it would be a good idea to create channels for sub-topics as it will help keep similar conversations together.

**Comment by what-name** [comment]
Yeah the seperate channels is definitely a must-have. My question is how seperated should each topic be? Wouldn't three or four for each provider be too much in total? This is better with Slack indeed that you can simply join only the channels you want to be in as opposed to being in everything on Discord.

#provider
#provider-resources
#provider-help
#provider-challenges
#provider-links

These are all that I could think of, where's the redundancy? I think 2-3 with each would be a great middle ground. One for general, one for help and maybe one for resources? Can the resources be in general or would that cause too much clutter?

I personally do not have much experience in creating communities like these. Just providing my 2 cents from a Junior perspective and spitballing ideas.

Also, @donofriov sorry for my harsh response. Slack is a great platform but in my opinion it is not easy to get started with or as easy to use as Discord, but maybe that's just me.

**Comment by kmoberg** [comment]
I agree with @donofriov that Slack could be a better alternative than Discord. Slacks signup process has become much easier, allowing you to generate a public link that anyone can use to join. They insert their email and select a password - done.

**Comment by omenking** [comment]
I have to use Slack and Discord on a regular basis.

The largest pain for me with Slack is:
* friction to manage multiple accounts across multiple computers and the signup process. It has not improved.
* Slack rich editor is very frustrating and glitchy most times. Such as upload images working with blocks of code.

Slack has threads, which is only great when people use them.

With Discord:
* you create one account, and you never have to make another account again. 
* You never get told you have too many messages or any kind of upsell
* It can integrate with streaming
* It is built to be community-focused where if you get to a certain size you can have a vanity URL and other features.
* Audio channels are great for hopping into impromptu meetings

Can we have both? I suppose, but I'm going to have split my energies into two different places.

**Comment by omenking** [comment]
We now have a Slack as well. But I'll primarily be in the Discord
[link removed]

Will see if anybody uses the Slack.

**Comment by donofriov** [comment]
Yeah I was just going based off my personal experience, I like Slack better and am more experienced with it, but I think it would benefit everyone to have the community in one place and not split. It's probably better to just remove the Slack account so we can continue to optimize the Discord.

**Comment by kmoberg** [comment]
Agreed, it's better to stick with one platform rather than splitting it into two. The community is not even close to large enough for that to work. 

I much prefer Slack to Discord (and I'm a part of 30+ Discord servers for various projects), but unless the community or admins/moderators are all in agreement with going with Slack I say stick with Discord.

**Comment by what-name** [comment]
What's the consensus on this? I did not sign up for the Slack channel, how active is it? In Discord there are currently 48 people and it's quite well built-out already in terms of channels. I think it's working very effectively, lack of threads is not a pain point. Decently active as well.

If Discord will become the go-to platform, I think we should start sharing it on Twitter. There are a lot of people participating in the 100DaysOfCloud challenge already on there, this would offer more access to help and to the community for them.

If consensus is reached, lets consider closing this issue.

**Comment by kmoberg** [comment]
Same; I haven't signed up for Slack either to not split the community. I agree - let's decided on one and close the other.

**Comment by madebygps** [comment]
@omenking  let's just close slack and this issue... what do you think, one less thing to worry about.

**Comment by omenking** [comment]
Yep lets close it. We gave it a go, and no one utilized it.
