### ISSUE TITLE
Enable required number of PR reviewers

### ISSUE THREAD

**Issue by what-name** [100DaysOfCloud/100DaysOfCloudIdeas#23]
### Issue
There have been PRs that had issues in them caught after the merge. The speed of adding new projects is important, but not at the cost of project idea quality. Realistically the chances of these issues getting fixed after merging are low, and it will go further down as the amount of projects increases.

### Solution
I propose to set the minimum required reviewers to three. This would eliminate most of the overlooked issues while also maintaining speed. This means that any three collaborators have to approve before a merge is allowed. Most of us are active every day.

### Resources
[Here is the GitHub blog post](https://github.blog/2018-03-23-require-multiple-reviewers/) on how to set up this guardrail.

**Comment by madebygps** [comment]
@what-name 3 is a lot, I can agree with 2... Keep in mind that we are volunteers and just getting started, a lot of this will get ironed out as we go, we can afford to make mistakes, just need to be a bit more careful.

**Comment by omenking** [comment]
I have set this for 2 reviewers for the time being and will increase to three in the coming weeks.

<img width="388" alt="Screen Shot 2020-07-12 at 7 07 38 PM" src="https://user-images.githubusercontent.com/7776/87258617-fe4d0e00-c472-11ea-8f9a-09039e0c22ff.png">
