### ISSUE TITLE
Set up an EFS share and mount it with two EC2 instances

### ISSUE THREAD

**Issue by what-name** [100DaysOfCloud/100DaysOfCloudIdeas#24]
### Choose the category (Choose only one, delete the remaining)
- Cloud Storage (STR) - STR03

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 200 (Intermediate)

### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- AWS

### You need to complete the following:
- Create an EFS file system 
- Spin up two EC2 instances with SSH allowed
- Mount the EFS share on both instances
- Create a file on the mounted EFS share from instance#1, open the same file from instance#2

### You need to answer the following:
- What network protocol does EFS use?
- How many instances can an EFS file share be mounted on simultaneously?
- How is the disk speed of an EFS volume determined?

## References
[Getting started with EFS](https://aws.amazon.com/getting-started/tutorials/create-network-file-system/)

## Costs
- 5GB of EFS file storage is included in the free tier

## Estimated time to complete
- 60-90 minutes

## Tips
- EFS file systems with a very low amount of data can be very slow.

**Comment by what-name** [comment]
good bot.

- Test of auto-labeler @johanrin 
- PR of new project idea incoming soon

**Comment by omenking** [comment]
looks good proceed to markdown
