### ISSUE TITLE
Adding cloud provider labels

### ISSUE THREAD

**Issue by KaranGauswami** [100DaysOfCloud/100DaysOfCloudIdeas#27]
**Is your feature request related to a problem? Please describe.**
Adding labels for cloud providers

**Describe the solution you'd like**
Add AWS,GCP and Azure to labeler.yml

**Additional context**

<img width="285" alt="label" src="https://user-images.githubusercontent.com/29201861/87309949-e214a400-c53a-11ea-9812-8988c20030ac.png">

**Comment by what-name** [comment]
Small modifications to #36 then close this issue.
