### ISSUE TITLE
DBS05-AWS100 - Create a DynamoDB table

### ISSUE THREAD

**Issue by what-name** [100DaysOfCloud/100DaysOfCloudIdeas#41]
### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)
- Databases (DBS)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 30 minutes

**Comment by madebygps** [comment]
Perfect, add the md and let's gooooooooo

**Comment by madebygps** [comment]
merged, amazing job on getting this quickly done
