### ISSUE TITLE
COM04-AWS100 - Push a Docker image to Amazon ECR repository

### ISSUE THREAD

**Issue by johanrin** [100DaysOfCloud/100DaysOfCloudIdeas#45]
### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)
- Cloud Computing (COM)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 30 minutes

**Comment by omenking** [comment]
Level looks good, proposal looks good. proceed to markdown file.
