### ISSUE TITLE
COM04-AWS200 - Deploy a Docker container image on AWS Fargate

### ISSUE THREAD

**Issue by johanrin** [100DaysOfCloud/100DaysOfCloudIdeas#46]
### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)
- Cloud Computing (COM)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 45 minutes

**Comment by omenking** [comment]
I think level 200.
Proposal good proceed to creating markdown
