### ISSUE TITLE
Deploy a CloudFormation  template from AWS Console

### ISSUE THREAD

**Issue by syedautherabbas** [100DaysOfCloud/100DaysOfCloudIdeas#49]
### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)

- DevOps (OPS)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 45-60 minutes

**Comment by what-name** [comment]
Great project idea. Couple thoughts:
- Do the participants have to write their own CloudFormation template or will a simple one be provided?
- If they should write their own template, this is a Level 200 project and the time frame should be 2 hours. As well as specifying what resources should be in the template.
- If one will be provided, will it be by us or one from AWS' own? I'm leaning towards providing our own with some basic resources and explaining what it does in detail. [AWS' sample template](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/GettingStarted.Walkthrough.html) deploys a whole Wordpress blog with a MySQL server, that's too much in my opinion. This would also allow participants to see what a simple template looks like and not get overwhelmed. I'm happy to write one up if needed as well.

Overall, I think this one should be Level 100 and a template provided by us (most likely hosted next to the project's .md file). After this, there could be another one Level 200 where they write their own template with resources that are specified in the project idea and using the CLI.

**Comment by what-name** [comment]
merged
