### ISSUE TITLE
STR04-AWS100 - Create an S3 Bucketand store an object on it

### ISSUE THREAD

**Issue by syedautherabbas** [100DaysOfCloud/100DaysOfCloudIdeas#51]
# Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)
- Cloud Storage (STR)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 15 minutes

**Comment by johanrin** [comment]
Typo in the title but the proposal looks good to me!
