### ISSUE TITLE
BIL02-AWS100 - Create a Cost Budget

### ISSUE THREAD

**Issue by ari-hacks** [100DaysOfCloud/100DaysOfCloudIdeas#58]
BIL02-AWS100 - Create a Cost Budget 

### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)
- Cloud Billing and Pricing (BIL)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
~ 1 hour (not sure yet)

## Objectives 
- Questions on budget best practices 
- Setup cost budget 

### References 
- [Create a budget](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/budgets-create.html#create-cost-budget)
- [Best practices](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/budgets-best-practices.html)

**Comment by what-name** [comment]
Great. Proceed to markdown👍

**Comment by madebygps** [comment]
Hi there, thanks for submitting this. I've merged this. I'll mention you forgot to add your project to the readme https://github.com/100DaysOfCloud/100DaysOfCloudIdeas/blob/master/README.md no worries, I'll update that and I'll add your name to the contributor list at the bottom.

**Comment by ari-hacks** [comment]
Awesome, thanks!
