### ISSUE TITLE
CPI: Set up billing alerts for $0 (free tier), $10 and $30

### ISSUE THREAD

**Issue by what-name** [100DaysOfCloud/100DaysOfCloudIdeas#6]
### Choose the category (Choose only one)
- Cloud Billing and Pricing

### Choose the level of difficulty (Please only choose one)

- Level 100 (Introductory)

### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud)
- AWS

### Do your best to calculate possible costs for free-tier and non-free-tier account
- No costs associated

### If you know of any external resources, provide the links
- [AWS Docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html)

### Tips
- By default, only the root user of the account can access the Billing dashboard. IAM user access to Billing has to be enabled seperately.

**Comment by what-name** [comment]
I went ahead and created the first project idea issue.

Idea:
- "Tips" section as seen above. This would be a place for detailing any _gotchas_ that come with a day of unnecessary troubleshooting.

Questions:
- Will the issues use the label "Cloud Project Idea" next to the Lvl. as proposed in #4 ? If not, is the "CPI" in the title a possible solution to seperate the ideas from the rest?
- Does this format work? Deleting everything from the issue template except for the desired text?
- Should the provider be in the title of the issue?

**Comment by omenking** [comment]
# The Submission

I would specify that the  first 10 Alarms are free.  https://aws.amazon.com/cloudwatch/pricing/ 

# Ideas

Good idea

# Questions

### Will the issues use the label "Cloud Project Idea" next to the Lvl. as proposed in #4 ? If not, is the "CPI" in the title a possible solution to separate the ideas from the rest?

Looks like @madebygps made an attempt to fill some in!
She's just linking the resource, though I think we'll need a bit more information around what to do.

I was thinking that  "BIL01 — Billing Alerts" would link to another markdown page. 
In there it would contain the projects per provider. And it is possible to multiple variants per provider.
Some subcategories or so specific that I could not see more than one per provider but I think we'll need a markdown page per subcategory or our overview page will get long very quickly.

<img width="772" alt="Screen Shot 2020-07-08 at 8 41 49 AM" src="https://user-images.githubusercontent.com/7776/86919902-e6822c80-c0f6-11ea-8506-1902013549b7.png">

We would then have another code based on the project eg. `BIL01-AWS100` 

* BIL01-AWS100 — AWS Project about Billing that is Level 100
* BIL01-AWS101 — Another AWS Project about Billing that is Level 100

### Does this format work? Deleting everything from the issue template except for the desired text?

Looking at it. I would probably add two extra sections comprised of either a sentence or a paragraph for each:

* compression (ask questions they need to figure out)
* goal (describe the goal in long-form eg. instructions without step-by-step information)

### Should the provider be in the title of the issue?

When we have a subcategory markdown pages I think we'll have headings per provider category.

**Comment by madebygps** [comment]
@omenking we can create a different page for each project and in there provide more info. I was just adding links here, but if we want to provide more info, yes creating a page is the way to do.

**Comment by omenking** [comment]
@madebygps it was great what you were doing. You can keep doing that until we get the pages in.

**Comment by omenking** [comment]
I just linked up the first one.
I am trying to figure out how to structure the internal page.

<img width="413" alt="Screen Shot 2020-07-08 at 9 15 33 AM" src="https://user-images.githubusercontent.com/7776/86923182-b5f0c180-c0fb-11ea-83c1-3bb186e155f8.png">

**Comment by omenking** [comment]
So I created the first sub-category page. Now looking at it, I considering breaking up each into their own markdown file and then linking them as a bulleted list as @madebygps was doing.

https://github.com/100DaysOfCloud/100DaysOfCloudIdeas/blob/master/BIL__Cloud-Billing-and-Pricing/BIL01__Billing-alerts.md

**Comment by omenking** [comment]
So I changed it to this. I think more manageable with individual files per project.
I don't like the look of the bulleted list lol
<img width="486" alt="Screen Shot 2020-07-08 at 10 28 18 AM" src="https://user-images.githubusercontent.com/7776/86931182-c9a12580-c105-11ea-888e-226526bd901e.png">

**Comment by omenking** [comment]
<img width="762" alt="Screen Shot 2020-07-08 at 10 37 52 AM" src="https://user-images.githubusercontent.com/7776/86932252-1f2a0200-c107-11ea-89bc-658ae05859d6.png">

**Comment by madebygps** [comment]
looks good! I'll continue adding with this format

**Comment by what-name** [comment]
## Questions:
- Should the sub-categories go into a central folder and fan out from there (f.e. `Projects`), or have seperate folders in the root directory for `BIL`, `SEC`, `GOV` etc? I think having them in the root directory (like it is right now) is better as it's not too abstracted.
- The `BIL01` table view looks great and gives easy access to the projects themselves. However, will the main README not become too hectic if every category will look like that? How to find the UI balance for just enough information so it's easy to consume but not too cluttered? Maybe it just stands out because it's alone right now.

## Misc
- [Own Markdown projects](https://github.com/100DaysOfCloud/100DaysOfCloudIdeas/tree/master/BIL/BIL01) - These look amazing! Also great idea on providing the author of the project. It both puts a person behind it and gives a "sense of stability" that there is someone to reach out to when you hit a roadblock.
- Project sub-IDs - This is great!
    > We would then have another code based on the project eg. BIL01-AWS100
       BIL01-AWS100 — AWS Project about Billing that is Level 100
       BIL01-AWS101 — Another AWS Project about Billing that is Level 100

**Comment by omenking** [comment]
## Q1

* Should the sub-categories go into a central folder and fan-out from there?
* or have separate folders in the root directory for BIL, SEC, GOV etc? 

Uncertain. The first is more organized, the second reduces the amount of text required to type to link them in the readme.
If we happen to have other things such as templates or etc that putting them under projects would be a good idea eg:

```
/projects
/templates
```

## Q2

Uncertain. I would say let's keep filling it and revisit its organization.
Having a big page shows the awe and scope of the community project, but I don't know yet if it will hinder the utility. 
I think we'll find out soon.

**Comment by omenking** [comment]
One thing I have not noted is that when people fill out their 100DaysOfCloud we can link their projects under a heading so people can then see who has done them and read others.

**Comment by what-name** [comment]
Since there have been a couple projects added, what is the experience? Should it be both the issue and the PR, or just the PR? I'm leaning towards the latter, a seperate issue is quite redundant and in my opinion does not offer any extra information over the PR, except the "Cost" section. I think adding that section to the PR template and removing the issue template would simplify the process.

### Questions:
- Should PRs go to their respective branch or to master? Since only collaborators can create branches, I think master would be sufficient, also one less step without merging the extra branch. 

### Misc:
- Projects folder structure is great
- Main README table structure/look is great, also the linked list on the top.

**Comment by what-name** [comment]
Move to #3
