### ISSUE TITLE
GLU07-AWS100 Setup a simple state machine with at least 2 steps 

### ISSUE THREAD

**Issue by syedautherabbas** [100DaysOfCloud/100DaysOfCloudIdeas#61]
### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)
- Application Integration (GLU)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 60 minutes

**Comment by what-name** [comment]
I'd put this on 200. Not necessarly because of it's difficulty, but that this is something for more in-depth use and not covered by the CCP. That's my 2 cents tho
