### ISSUE TITLE
DEV03-AWS100 - Install/Configure AWS CLI then create an S3 bucket 

### ISSUE THREAD

**Issue by ari-hacks** [100DaysOfCloud/100DaysOfCloudIdeas#68]
### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)
- Developer Tools (DEV)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 20-30 minutes

**Comment by johanrin** [comment]
It looks good to me!

**Comment by what-name** [comment]
I'm not sure if this should be 100. There are a lot of steps to this:
- Make sure to have an IAM user
- Create access/secret keys in the console
- Install the AWS CLI on your operating system (different workflow for each)
- Run `aws configure` and set up the keys and everything
- Create bucket with `aws s3api create-bucket xyz`
- Make sure bucket is there (console is enough)

Yeah maybe 100, true. But please describe the steps in detail.

**Comment by ari-hacks** [comment]
ok, will do 🙂
