### ISSUE TITLE
Introduction to Simple Notification Service

### ISSUE THREAD

**Issue by edwardmercado** [100DaysOfCloud/100DaysOfCloudIdeas#72]
# GLU02-AWS100 - Introduction to SNS (Simple Notification Service)

## Cloud Service Provider
- Amazon Web Services

## Difficulty
- Level 100 (Introductory)

## Project's Author(s)

- [Edward Allen Mercado](https://twitter.com/edwardmercado_)

### You need to complete the following:

- Create a SNS Topic
- Subscribe to a SNS Topic
- Receive email notification from the SNS Topic created

### You need to answer the following:

- What is SNS?
- How Pub/Sub notifications work?
- What are the different endpoints that SNS can send notification?

## References

- [AWS SNS Official Documentation](https://docs.aws.amazon.com/sns/latest/dg/welcome.html)

## Costs

- Included in the Free Tier
- As part of AWS’s Free Usage Tier, new AWS customers will receive free 15 GB of data transfer out each month aggregated across all AWS services for one year.

## Estimated time to complete

- 15 minutes

**Comment by what-name** [comment]
Time to complete should be 30min
Looks good, proceed to PR😎

**Comment by edwardmercado** [comment]
submitted to PR
Time to Complete modified to 30 mins
