### ISSUE TITLE
DBS03-AWS100 - Creating an Amazon RDS DB Instance (MS SQL Server)

### ISSUE THREAD

**Issue by JAG-010** [100DaysOfCloud/100DaysOfCloudIdeas#76]
### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)

- Databases (DBS)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 45-60 minutes

**Comment by madebygps** [comment]
Great work 💯
