### ISSUE TITLE
OPS01-AWS300 - Deploy a VPC with Terraform 

### ISSUE THREAD

**Issue by Mapmark** [100DaysOfCloud/100DaysOfCloudIdeas#78]
### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 300 (Advanced)

### Choose the category (Please only choose one, delete the remaining)
- DevOps (OPS)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 60 minutes 

# Additional Information 
- Create a VPC
- Create Internet Gateway 
- Create Route tables (Public / Private )
- Create Subnet (public / Private) 
- Create Security Groups 
- Create resources to launch   Ec2 Instance in both Public & Private Subnet
- Output public IP of Ec2 Instances 
- (Optional) - Pass in User Data to create webserver for Public instance.

**Comment by omenking** [comment]
I'd love to see a Terraform example.
Proceed to write up the markdown file

**Comment by madebygps** [comment]
Great work :)
