### ISSUE TITLE
Alexa Skill

### ISSUE THREAD

**Issue by what-name** [100DaysOfCloud/100DaysOfCloudIdeas#8]
As shown on Twitter before, I think an Alexa skill would be a cool little quirk for the 100DaysOfCloud movement. I don't think it needs to have that much functionality and it's suprisingly easy to develop. I have created a simple back-and-forth conversation that tells a "project of the day" in a couple hours (with no experience). The backend is simply a Lambda function written in Python or NodeJS. 

💰 Alexa Skills are free to host - as far as I can tell - up to 1 million requests/month (which will not be exceeded) and 400,000 GB/s. It is done through the developer console but can be deployed with a custom solution on AWS as well.

### Functionality ideas
- Today's project - every day Alexa would have a different project to do with a short explanation.
- More info about 100DaysOfCloud - Some basic information on what the movement is and where to get more information.
- Currently the response is hardcoded but could be scraped from this repo as well automatically.

### Example of back-and-forth conversation
[Video available here (turn on audio)](https://imgur.com/a/6gFsCnZ)

I can definitely take on the creation of the skill alone if needed, however I'd love some feedback on what it should be like and what functionality it should have.

**Comment by omenking** [comment]
I can't think of any other functionality other than:
* Todays Challenge
* What's my progress eg. 2/100

**Comment by syedautherabbas** [comment]
I think we can create a leaderboard section in the skill, based on contributions to OSS for #100daysofcloud based repos /blogs articles AND/OR tweets with the #100daysofcloud and display those leaderboards on the https://100daysofcloud.com/ site under some interesting name like #halloffame or most active contributors.

**Comment by what-name** [comment]
Moved to [100DaysOfCloudRoadmap/#6](https://github.com/100DaysOfCloud/100DaysOfCloudRoadmap/issues/6).
