### ISSUE TITLE
DBS03-AWS101 - Creating an Aurora Database

### ISSUE THREAD

**Issue by hatchcanon** [100DaysOfCloud/100DaysOfCloudIdeas#80]
### Choose the Cloud Service Provider
- Amazon Web Services

### Choose the level of difficulty 
- Level 100 (Introductory)

### Choose the category 
- Databases (DBS)

### Project's Author
- [Nathan Cho](https://github.com/hatchcanon)

### Calculate the estimated time required to complete this project
- 1-1.5 hours

## Additional Info
- Create an Amazon VPC for Use with a DB Instance 
- Create a VPC with Private and Public Subnets
- Create Additional Subnets
- Create a VPC Security Group for a Public Web Server
- Create a VPC Security Group for a Private DB Instance
- Create an Aurora DB
- Verify with MySQL Workbench

**Comment by madebygps** [comment]
Looks great! Open a PR with the markdown of the project when you can :)

**Comment by madebygps** [comment]
Merged
